/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-16 17:24:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class booted_005ffunctions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/codyh/eclipse-jee-workspace/Dealership/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/CarDealershipProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1599869395813L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Cody's Car Lot</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./styles/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow\">\r\n");
      out.write("  \t\t<a class=\"navbar-brand col-md-3 col-lg-2 mr-0 px-3\" href=\"#\">Cody's Car Lot</a>\r\n");
      out.write("  \t\t\t<button class=\"navbar-toggler position-absolute d-md-none collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#sidebarMenu\" aria-controls=\"sidebarMenu\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    \t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  \t\t\t</button>\r\n");
      out.write("  \t\t<input class=\"form-control form-control-dark w-100\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("  \t\t<ul class=\"navbar-nav px-3\">\r\n");
      out.write("    \t\t<li class=\"nav-item text-nowrap\">\r\n");
      out.write("      \t\t\t<a class=\"nav-link\" href=\"#\">Sign out</a>\r\n");
      out.write("    \t\t</li>\r\n");
      out.write("  \t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"jumbotron\">\r\n");
      out.write("    \t<div class=\"container\">\r\n");
      out.write("      \t\t<h1 class=\"display-3\">Welcome to the Business Functions Page</h1>\r\n");
      out.write("      \t\t<p>Use this page to create/sell/remove/update inventory.</p>\r\n");
      out.write("    \t</div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("  \t\t<div class=\"row\">\r\n");
      out.write("    \t\t<nav id=\"sidebarMenu\" class=\"col-md-3 col-lg-2 d-md-block bg-light sidebar collapse show\" style=\"\">\r\n");
      out.write("      \t\t\t<div class=\"sidebar-sticky pt-3\">\r\n");
      out.write("        \t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("          \t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("            \t\t\t\t<a class=\"nav-link active\" href=\"booted_home.jsp\">\r\n");
      out.write("              \t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-home\"><path d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"></path><polyline points=\"9 22 9 12 15 12 15 22\"></polyline></svg>\r\n");
      out.write("              \t\t\t\t\tHome Page\r\n");
      out.write("            \t\t\t\t</a>\r\n");
      out.write("          \t\t\t\t</li>\r\n");
      out.write("          \t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("            \t\t\t\t<a class=\"nav-link\" href=\"booted_inventory.jsp\">\r\n");
      out.write("              \t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-file\"><path d=\"M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z\"></path><polyline points=\"13 2 13 9 20 9\"></polyline></svg>\r\n");
      out.write("              \t\t\t\t\tInventory\r\n");
      out.write("            \t\t\t\t</a>\r\n");
      out.write("          \t\t\t\t</li>\r\n");
      out.write("          \t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("            \t\t\t\t<a class=\"nav-link\" href=\"booted_auction.jsp\">\r\n");
      out.write("              \t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-shopping-cart\"><circle cx=\"9\" cy=\"21\" r=\"1\"></circle><circle cx=\"20\" cy=\"21\" r=\"1\"></circle><path d=\"M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6\"></path></svg>\r\n");
      out.write("              \t\t\t\t\tAuction Page \r\n");
      out.write("            \t\t\t\t</a>\r\n");
      out.write("          \t\t\t\t</li>\r\n");
      out.write("          \t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("            \t\t\t\t<a class=\"nav-link\" href=\"booted_functions.jsp\">\r\n");
      out.write("              \t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-users\"><path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"></path><circle cx=\"9\" cy=\"7\" r=\"4\"></circle><path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"></path><path d=\"M16 3.13a4 4 0 0 1 0 7.75\"></path></svg>\r\n");
      out.write("              \t\t\t\t\tBusiness Page - Functions <span class=\"sr-only\">(current)</span>\r\n");
      out.write("            \t\t\t\t</a>\r\n");
      out.write("          \t\t\t\t</li>\r\n");
      out.write("          \t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("            \t\t\t\t<a class=\"nav-link\" href=\"booted_reports.jsp\">\r\n");
      out.write("              \t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-bar-chart-2\"><line x1=\"18\" y1=\"20\" x2=\"18\" y2=\"10\"></line><line x1=\"12\" y1=\"20\" x2=\"12\" y2=\"4\"></line><line x1=\"6\" y1=\"20\" x2=\"6\" y2=\"14\"></line></svg>\r\n");
      out.write("             \t \t\t\t\tBusiness Page - Reports\r\n");
      out.write("            \t\t\t\t</a>\r\n");
      out.write("          \t\t\t\t</li>\r\n");
      out.write("        \t\t\t</ul>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("    \t\t</nav>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"inventoryUpdateServlet\" method=\"post\">\r\n");
      out.write("  \t\t<div class=\"form-row\">\r\n");
      out.write("  \t\t\t<div class=\"form-group col-md-2\">\r\n");
      out.write("      \t\t\t<select name=\"action\" id=\"action\" class=\"form-control\">\r\n");
      out.write("      \t\t\t\t<option>Select Action...</option>\r\n");
      out.write("      \t\t\t\t<option value=\"add\">Add</option>\r\n");
      out.write("      \t\t\t\t<option value=\"remove\">Remove</option>\r\n");
      out.write("      \t\t\t\t<option value=\"sell\">Sell</option>\r\n");
      out.write("      \t\t\t</select>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"form-group col-md-2\">\r\n");
      out.write("      \t\t\t<select name=\"make\" id=\"make\" class=\"form-control\">\r\n");
      out.write("      \t\t\t\t<option>Select Make...</option>\r\n");
      out.write("      \t\t\t\t<option value=\"mazda\">Mazda</option>\r\n");
      out.write("      \t\t\t\t<option value=\"ford\">Ford</option>\r\n");
      out.write("      \t\t\t\t<option value=\"toyota\">Toyota</option>\r\n");
      out.write("      \t\t\t</select>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"form-group col-md-2\">\r\n");
      out.write("      \t\t\t<select name=\"model\" id=\"model\" class=\"form-control\">\r\n");
      out.write("      \t\t\t\t<option>Select Model...</option>\r\n");
      out.write("      \t\t\t\t<option value=\"mazda3\">Mazda3</option>\r\n");
      out.write("      \t\t\t\t<option value=\"cx5\">CX5</option>\r\n");
      out.write("      \t\t\t\t<option value=\"corolla\">Corolla</option>\r\n");
      out.write("      \t\t\t\t<option value=\"mustang\">Mustang</option>\r\n");
      out.write("      \t\t\t</select>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"vin\">VIN: </label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"vin\" id=\"vin\" placeholder=\"ex. 1234M\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"ownerName\">Owner Name: </label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"ownerName\" id=\"ownerName\" placeholder=\"Name\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"msrp\">MSRP: </label>\r\n");
      out.write("\t\t\t$<input type=\"text\" class=\"form-control col-md-2\" name=\"msrp\" id=\"msrp\" placeholder=\"19000\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"year\">Year: </label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"year\" id=\"year\" placeholder=\"year\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"odometer\">Odometer: </label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"odometer\" id=\"odometer\" placeholder=\"ex. 10000\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<h4>Dealer purchase date:</h4>\r\n");
      out.write("\t\t\t\t\t<label for=\"dealer-mm\">Month</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"dealer-mm\" id=\"dealer-mm\">\r\n");
      out.write("\t\t\t\t\t<label for=\"dealer-dd\">Day</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"dealer-dd\" id=\"dealer-dd\">\r\n");
      out.write("\t\t\t\t\t<label for=\"dealer-yyyy\">Year</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"dealer-yyyy\" id=\"dealer-yyyy\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("    \t<div class=\"form-group col-md-2\">\r\n");
      out.write("      \t\t<label for=\"color\">Color</label>\r\n");
      out.write("      \t\t<select name=\"color\" id=\"color\" class=\"form-control\">\r\n");
      out.write("        \t\t\t<option selected>Choose...</option>\r\n");
      out.write("        \t\t\t<option value=\"BLACK\">Black</option>\r\n");
      out.write("        \t\t\t<option value=\"BLUE\">Blue</option>\r\n");
      out.write("        \t\t\t<option value=\"GREEN\">Green</option>\r\n");
      out.write("        \t\t\t<option value=\"RED\">Red</option>\r\n");
      out.write("        \t\t\t<option value=\"WHITE\">White</option>\r\n");
      out.write("      \t\t\t</select>\r\n");
      out.write("    \t</div>  \t\t\r\n");
      out.write("  \t\t<div class=\"form-group col-md-2\">\r\n");
      out.write("\t\t\t<select class=\"form-control\" name=\"condition\" id=\"condition\">\r\n");
      out.write("\t\t\t\t<option value=\"new\">New</option>\r\n");
      out.write("\t\t\t\t<option value=\"used\">Used</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"ownerName\">Owner Name: </label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"buyerName\" id=\"buyerName\" placeholder=\"Name\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h3>***This section is only for the action \"Sell\"***</h3>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<h4>Owner purchase date:</h4>\r\n");
      out.write("\t\t\t\t\t<label for=\"soldMm\">Month</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"soldMm\" id=\"soldMm\">\r\n");
      out.write("\t\t\t\t\t<label for=\"soldDd\">Day</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"soldDd\" id=\"soldDd\">\r\n");
      out.write("\t\t\t\t\t<label for=\"soldYyyy\">Year</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control col-md-2\" name=\"soldYyyy\" id=\"soldYyyy\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("  \t\t<button type=\"submit\" class=\"btn btn-primary\">Submit</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
